version: '3'

services:
  airflow:
    build:
      context: ./
    container_name: airflow
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "(
        airflow db init &&
        airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email example@example.org
      );
      airflow webserver &
      airflow scheduler
      "
  events-api:
    build: ./events-api/
    container_name: events-api